enum Fonts {
  JAKARTA_SANS,
  ROBOTO,
  FIGTREE,
  NUNITO,
  PLAYFAIR_DISPLAY,
  POPPINS,
  LORA,
  OSWALD,
  BEBAS_NEUE,
  QUESTRIAL,
  KANIT
}

enum TextFieldType { OUTLINED, UNDERLINE }

enum ButtonType { OUTLINE, FILL }

enum ButtonColor { PRIMARY, INFO, WARNING, SUCCESS, ERROR }

enum AppLocale { ID, EN }
